import RecordItem from "./record-item";

export const mockAlbums: Array<RecordItem> = [
  {
    _id: "1",
    name: "Albino",
    artist: "Joost",
    isBand: false,
    price: 12.4,
    releaseDate: new Date(2019, 1, 18),
  },
  {
    _id: "2",
    name: "Very long album name, like very long, very long, yeah",
    artist: "Very cool artist i guess, very, very cool",
    isBand: false,
    price: 12.4,
    releaseDate: new Date(2019, 1, 18),
  },
  {
    _id: "4",
    name: "So Gut",
    artist: "Joost",
    isBand: false,
    price: 12.4,
    releaseDate: new Date(2019, 1, 18),
  },
  {
    _id: "3",
    name: "Breaking Bad",
    artist: "Joost",
    isBand: false,
    price: 12.4,
    releaseDate: new Date(2019, 1, 18),
  },
  {
    _id: "25",
    name: "Sensuhct",
    artist: "Joost",
    isBand: true,
    price: 12.4,
    releaseDate: new Date(2019, 1, 18),
  },
  {
    _id: "134",
    name: "Antricot",
    artist: "Joost",
    isBand: false,
    price: 12.4,
    releaseDate: new Date(2019, 1, 18),
  },
  {
    _id: "11",
    name: "Album",
    artist: "Joost",
    isBand: false,
    price: 12.4,
    releaseDate: new Date(2019, 1, 18),
  },
];
